# Generated by Django 4.0.1 on 2022-01-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='download_links',
            field=models.TextField(default='', max_length=100000000000000000000000),
        ),
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.TextField(max_length=300000000000000000000000000000000),
        ),
    ]
