# Generated by Django 4.0.1 on 2022-01-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_video_blogcomment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
