# Generated by Django 4.0.1 on 2022-01-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_comment_subcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comm',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Home.comment'),
        ),
        migrations.DeleteModel(
            name='SubComment',
        ),
    ]
