# Generated by Django 4.0.1 on 2022-01-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_time_comment_timestamp_remove_comment_comm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
