# Generated by Django 4.0.1 on 2022-01-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_comment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=5000000)),
                ('desc', models.TextField()),
                ('show_desc', models.CharField(max_length=68, null=True)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='download_links',
            field=models.TextField(default=''),
        ),
    ]
