# Generated by Django 4.0.1 on 2022-01-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_blog_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
